# Architecture override (auto if empty)

ARCH=amd64

# Kubernetes ecosystem
KUBECTL_VERSION=v1.29.15
HELM_VERSION=v4.1.1
K9S_VERSION=v0.50.18
STERN_VERSION=v1.33.1

# CLI utilities
JQ_VERSION=jq-1.8.1
YQ_VERSION=v4.52.4

# Registry tools
CRANE_VERSION=v0.21.1
KRANE_VERSION=v0.21.1
REGCTL_VERSION=v0.11.2
SKOPEO_VERSION=v1.22.0

# etcd
ETCD_VERSION=v3.6.8

# Container runtime stack
CONTAINERD_VERSION=v2.2.1
NERDCTL_VERSION=v2.2.1
RUNC_VERSION=v1.4.0
CNI_VERSION=v1.9.0
